User cart favorites route
afonsocardz/projeto14-autoshop-back pull request #11
Opened 2022-07-09 05:19 UTC by dr1co

2022-07-09 13:51 UTC, dr1co commented
Criei um middleware de validar token, mas posso excluir esse arquivo depois pois não será mais necessário, já que você tinha criado um já e eu fui perceber depois .__.

2022-07-10 01:41 UTC, afonsocardz requested changes
Acho que para adicionar o produto não é necessário dar find em token, pois a rota é autenticada através do middleware, pode localizar apenas por email eu acho.

2022-07-11 13:39 UTC, dr1co reviewed
tirei o arquivo :dancers:

2022-07-11 19:04 UTC, afonsocardz approved these changes
Show!

2022-07-11 19:04 UTC, merged